#!/usr/bin/env bash

# install-deps.sh --
#
# A script to install deps for NintendoDS game development.
#
# Copyright (C) 2026 Pablo Trik Marin
# License GPL 2.0

err() {
        echo -e "\e[31merror: $1\e[0m"
        exit 1
}

if ! type pacman 2>&1 >/dev/null; then
        err 'You need pacman to install deps :('
fi

if [[ $USER != root ]]; then
        err 'You need to run the script as root. Always use root for everything!'
fi

# From now on...
# This is AI-slop: run at your own risk!!!!
# Installation instructions at: https://devkitpro.org/wiki/devkitPro_pacman

set -e

PACMAN_CONF="/etc/pacman.conf"
BASHRC="/root/.bashrc"

if ! grep -q '^\[dkp-libs\]$' "$PACMAN_CONF"; then
    cat >> "$PACMAN_CONF" <<'EOF'

[dkp-libs]
Server = https://pkg.devkitpro.org/packages

[dkp-linux]
Server = https://pkg.devkitpro.org/packages/linux/$arch
EOF
fi

if ! grep -q '^export DEVKITPRO=' "$BASHRC"; then
    cat >> "$BASHRC" <<'EOF'

export DEVKITPRO=/opt/devkitpro
export DEVKITARM=/opt/devkitpro/devkitARM
export DEVKITPPC=/opt/devkitpro/devkitPPC
export PATH="$PATH:/opt/devkitpro/devkitARM/bin/"
export PATH="$PATH:/opt/devkitpro/tools/bin/"
EOF
fi

pacman-key --recv \
    BC26F752D25B92CE272E0F44F7FD5492264BB9D0 \
    --keyserver keyserver.ubuntu.com

pacman-key --lsign \
    BC26F752D25B92CE272E0F44F7FD5492264BB9D0

pacman -U \
    https://pkg.devkitpro.org/devkitpro-keyring.pkg.tar.zst

pacman -Syu

pacman -S make
pacman -S nds-dev

echo 'Now run "$ source ~/.bashrc"'
